### ISSUE TITLE
"crashes dedicate server b1341 during load"

### ISSUE THREAD

**Issue by kreezxil** [WVAviator/LandDefender#1]
server crash report: http://pastebin.com/SwuXSUWX
server fml latest: http://pastebin.com/cTtk3tBL

**Comment by WVAviator** [comment]
Is this the first time you loaded the mod?
Check the Land Defender folder inside your config folder. There should be a sqlite driver .jar file and a database chunks.db. Are those in there?

**Comment by kreezxil** [comment]
I ran it twice with the same result. Only the jar file was in that directory, the db file didn't get created.

Also, I just ran it twice again, same result.

server craash report on startup: http://pastebin.com/K0AxLb3C
server fml latest on startup: http://pastebin.com/gqyNgu08

-----Original Message-----

**Comment by kreezxil** [comment]
This is the filename of the jarfile:
sqlite-jdbc-3.8.7.jarsqlite-jdbc-3.8.7.jar

seems unusually long, like the two filenames you expected got jammed together. which could explain the crash.

**Comment by WVAviator** [comment]
Try renaming that to just sqlite-jdbc-3.8.7.jar and delete the database and restart. Should work fine then, and I'll try to figure out why it doubles up on the name for you but works fine for me. What OS are you running this on?

**Comment by WVAviator** [comment]
Also, are you downloading the version on curseforge or the one here in the github repository?

**Comment by WVAviator** [comment]
I spotted the problem in the code. I will fix it as soon as possible. Thank you for letting me know about this

**Comment by kreezxil** [comment]
Sure thing 😊 

-----Original Message-----

**Comment by kreezxil** [comment]
The server is 64 bit Ubuntu Linux 14.04. 

-----Original Message-----

**Comment by WVAviator** [comment]
Fixed for version 0.2.1. :)

**Comment by kreezxil** [comment]
Thanks

-----Original Message-----
