### ISSUE TITLE
[Suggestion] Ability to give more chunk space

### ISSUE THREAD

**Issue by Scootty** [WVAviator/LandDefender#3]
Not sure if this is the right place, but it said on your forge page to leave suggestions here so my suggestion is to allow admins to give players additional space. This mod looks a lot like /home and could very well be a viable replacement if they can teleport to claimed chunks. Also, if the command could then be used by votifier.

**Comment by WVAviator** [comment]
Just added /claimadd <player> <claims> for ops to add to a players total allowed claims. You should be able to have votifier run this command with /claimadd Scootty 1 or something, in that instance Scootty will receive 1 additional claim per vote. ALso added /claimsubtract and /claimset.
